name: CI (no bloqueante)

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (best-effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest >/dev/null 2>&1 || true

      - name: Run tests (non-blocking)
        continue-on-error: true
        run: |
          if command -v pytest >/dev/null 2>&1; then
            echo "Ejecutando pytest…"
            pytest -q || true
          else
            echo "pytest no está disponible; se omiten tests."
          fi
