name: Test and build

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"   # password vacío para root
          MYSQL_DATABASE: fumigaciones_db     # coincide con tu config.py
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system packages for mysqlclient
        run: |
          sudo apt-get update
          sudo apt-get install -y default-libmysqlclient-dev build-essential

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be healthy
        run: |
          for i in {1..30}; do
            mysqladmin ping -h 127.0.0.1 --silent && break
            sleep 2
          done

      - name: Run tests with coverage
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
          MYSQL_DB: fumigaciones_db
        run: |
          pytest -q --cov=src --cov-report=term-missing
