name: Test and build

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Add src to PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

    - name: Lint
      run: |
        pip install flake8
        flake8 src tests

    - name: Run tests with coverage
      run: |
        pip install pytest pytest-cov
        pytest -q --cov=src --cov-report=term-missing
